export default {
  NODE_END: Symbol('NODE_END'),
  NODE_VENTURE_START: Symbol('NODE_VENTRUE_START'),
  NODE_START: Symbol('NODE_START'),
  NODE_VENTURE_START_CONFIRM: Symbol('NODE_VENTURE_START_CONFIRM'),
  NODE_VENTURE_START_DROP: Symbol('NODE_VENTURE_START_DROP'),
};